# Generated by Django 3.1 on 2020-09-17 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_auto_20200917_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='comments',
            field=models.ManyToManyField(related_name='ad_comments', through='ads.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
