# Generated by Django 3.1 on 2024-11-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0002_auto_20241105_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('RR', 'Round Robin'), ('QF', 'Qualifier'), ('SF', 'Semi Final'), ('F', 'Final')], default='RR', max_length=2),
        ),
    ]
