# Generated by Django 3.1 on 2024-11-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0004_auto_20241105_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('RR', 'Round Robin'), ('Q', 'Qualifier'), ('E', 'Eliminator'), ('SF', 'Semi Final'), ('F', 'Final')], default='RR', max_length=2),
        ),
    ]
