# Generated by Django 3.1 on 2024-12-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0005_auto_20241105_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('Qualifier/Eliminator', 'Qualifier/Eliminator'), ('1V4|2V3', '1V4|2V3')], default='Qualifier/Eliminator', max_length=20),
        ),
    ]
